### PR TITLE
Refactored the project using https://github.com/dar5hak/generator-awe…

### PR DESCRIPTION
**Pull request by romellogood**
…some-list. Updated contributing guidelines.

@mxstbr @philpl i refactored the list and would love to get your feedback before merging in. I'm going to try to get this list added to https://github.com/sindresorhus/awesome after this PR is merged.

### CODE REVIEW

**Comment by romellogood** [comment]
New readme can be viewed here - [README.md](https://github.com/romellogood/awesome-styled-components/tree/awesome-refactor)

**Comment by romellogood** [comment]
Sounds good to me. Will transfer over to the organization right now

**Comment by mxstbr** [comment]
I've added you to the organisation, you should be able to transfer it from this repos settings!

**Comment by philpl** [comment]
@mxstbr Nice to finally have this in the org! :tada:

**Pull request merged**
